### ISSUE TITLE
code generation

### ISSUE THREAD

**Issue by cn-kali-team** [rhaiscript/rhai#501]
Is there a code generation tool? Do I want to batch convert from yaml files to rhai scripts, or can I use AST to code?

**Comment by schungx** [comment]
What do you mean by code generation tool?

Usually you just output Rhai script text.  There is no need to work with the AST.

If you want to convert YAML to Rhai, you can consider using a `handlebars` engine to generate scripts based on a template.

**Comment by cn-kali-team** [comment]
- I used yaml as a plug-in before, but it is not flexible, so I want to convert to rhai. I need to convert from yaml to rhai. Thank you for your suggestion. I am trying to use 'handlebars' to write a template to convert yaml to rhai. I hope it will work.
- like this
```yaml
requests:
  - method: GET
    path:
      - `${URL}/`

    matchers:
      - opt: contains
        words:
          - "some string"
        part: body
```
- convert
```rust
fn main(){
    let session = http::session();
    let rep = session.requests("GET",`${URL}/`);
    if rep.body.contains("some string"){
        print("yes");
    }
}
```
- I think we need a simple code to generate expressions and functions, which makes it easier to write rhai code.
