### ISSUE TITLE
Failed to resolve import "env" from "..\pkg\bench_rhai_console_bg.wasm" when using Engine instance

### ISSUE THREAD

**Issue by charleshetier** [rhaiscript/rhai#777]
Hello,

I am very new to rust and wasm (but experimented with js node and npm), I have an error I don't know how to solve while using rhai in a rust wasm_bindgen project on a web page.

Here is my lib source:
```rust
use wasm_bindgen::prelude::*;
use rhai::{Engine, Scope};

#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;
// static engine: Mutex<Engine> = Mutex::new(Engine::new());

#[wasm_bindgen]
pub struct BenchConsole {
    scope: Scope<'static>
}

#[wasm_bindgen]
impl BenchConsole {

    #[wasm_bindgen]
    pub fn eval_expression(&mut self, expression: &str) -> String {
        // String::from("Hello")
        match Engine::new().eval_with_scope(&mut self.scope, expression) {
            Ok(result) => result,
            Err(error) => error.to_string(),
        }
    }

    #[wasm_bindgen]
    pub fn new() -> BenchConsole {
        BenchConsole {
            scope: Scope::new()
        }
    }
}
```

The rust part compiles fine

But when building js part of the project (I tried both vite and webpack whith the same result) - vite output as few more details:

`Failed to resolve import "env" from "..\pkg\bench_rhai_console_bg.wasm". Does the file exist?
C:/_WS/bench-rhai-console/pkg/bench_rhai_console_bg.wasm:7:48`

Here is my cargo file:
```toml
[package]
xxx

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.88"
getrandom = { version = "0.2.10", features = ["js"] }
rhai = {version = "1.16.3", features = ["unchecked", "only_i32", "f32_float", "no_module"]}
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
#opt-level = "s"
opt-level = 0
```

The strange thing is that if I remove the use of Engine from my eval_expression function, it works fine even at runtime:

```rust
    #[wasm_bindgen]
    pub fn eval_expression(&mut self, expression: &str) -> String {
        String::from("Hello") // Works perfectly
        // match Engine::new().eval_with_scope(&mut self.scope, expression) {
        //     Ok(result) => result,
        //     Err(error) => error.to_string(),
       //  }
    }
```

I also tried to embed Engine as a field next to scope field

I am missing something ?
