### ISSUE TITLE
Getrandom failure upon building for WASM?

### ISSUE THREAD

**Issue by mahlquistj** [rhaiscript/rhai#997]
When building for WASM, with the `wasm-bindgen` feature enabled, i keep getting the same error:
```
error: The "wasm_js" backend requires the `wasm_js` feature for `getrandom`. For more information see: https://docs.rs/getrandom/0.3.3/#webassembly-support
  --> /home/maj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/getrandom-0.3.3/src/backends.rs:34:17
   |
34 | / ...   compile_error!(concat!(
35 | | ...       "The \"wasm_js\" backend requires the `wasm_js` feature \
36 | | ...       for `getrandom`. For more information see: \
37 | | ...       https://docs.rs/getrandom/", env!("CARGO_PKG_VERSION"), "/#webassembly...
38 | | ...   ));
   | |________^
```

I have rhai set as this in my workspace Cargo.toml:
```toml
rhai = "1.22"
```

And in my binary's Cargo.toml:
```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
rhai = { workspace = true, features = ["wasm-bindgen"] }
```

Upon removing rhai from the dependencies, it compiles just fine
